config/routes.rb
GlassVision::Application.routes.draw do

  resources :emails
  match '/signup', :to => 'users#new', :as => :signup
  match '/login', :to => 'session#new', :as => :login
  match '/logout', :to => 'session#destroy', :as => :logout
  match '/activate/:id', :to => 'accounts#show', :as => :activate
  match '/forgot_password', :to => 'passwords#new', :as => :forgot_password
  match '/reset_password/:id', :to => 'passwords#edit', :as => :reset_password
  match '/change_password', :to => 'accounts#edit', :as => :change_password

  resources :users do
    post :enable
    post :disable
    resource :account
    resources :roles
  end

  resources :product_colors
  resources :shapes

  resources :doors do
    collection do
      get 'configure_panels'
      get 'configure_panel_dimensions'
      get 'configure_glass_families'
      get 'configure_glasses'
      get 'configure_openings'
    end
  end
  resources :door_frames
  resources :door_combinations
  resources :frame_profiles
  resources :slab_materials
  resources :door_openings
  resources :door_glass_families do
    resources :door_glasses
  end
  resources :door_panel_families do
    resources :door_panels do
      resources :door_panel_dimensions
    end
  end
  resources :door_borings
  resources :door_sections
  resources :manual_lines

  resource :session, :controller => :session
  resource :passwords
  resources :quotations, :controller => :quotation do
    collection do
        post :search
    end
    post :copy
    get :print
    get :print_invoice
    get :print_calculations
    get :print_manifest
  end
  root :to => 'home#index'

  match '/:controller(/:action(/:id))'
end

app/models/door_glass_family.rb
class DoorGlassFamily < ActiveRecord::Base
  has_many :door_glasses, :dependent => :destroy
end

app/controllers/door_glass_families_controller.rb
class DoorGlassFamiliesController < ApplicationController

  def index
    @door_glass_families = DoorGlassFamily.all(:order => :name)
  end

  def new
    @door_glass_family = DoorGlassFamily.new
  end

  def create
    @door_glass_family = DoorGlassFamily.new(params[:door_glass_family])
    if @door_glass_family.save
      flash[:notice] = trn_geth('LABEL_DOOR_GLASS_FAMILY') + " " + trn_get('MSG_SUCCESSFULLY_CREATED_F')
      redirect_to door_glass_families_path
    else
      render :action => 'new'
    end
  end

  def edit
    @door_glass_family = DoorGlassFamily.find(params[:id])
  end

  def update
    @door_glass_family = DoorGlassFamily.find(params[:id])
    if @door_glass_family.update_attributes(params[:door_glass_family])
      flash[:notice] = trn_geth('LABEL_DOOR_GLASS_FAMILY') + " " + trn_get('MSG_SUCCESSFULLY_MODIFIED_F')
      redirect_to door_glass_families_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    DoorGlassFamily.find(params[:id]).destroy
    flash[:notice] = trn_geth('LABEL_DOOR_GLASS_FAMILY') + " " + trn_get('MSG_SUCCESSFULLY_DELETED_F')
    redirect_to door_glass_families_path
  end

end

app/helpers/door_glass_families_helper.rb
module DoorGlassFamiliesHelper
end

app/views/door_glass_families/_form.html.erb
<%= error_messages_for "door_glass_family" %>

<table>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_NAME') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field "door_glass_family", "name", :size => 30 %></td>
  </tr>
</table>

app/views/door_glass_families/edit.html.erb
<h2><%= trn_get('TITLE_DOOR_GLASS_FAMILY_EDIT') %></h2>

<%= form_for @door_glass_family do |f| %>
  <%= render :partial => 'form' %>
  <%= submit_tag trn_geth('BUTTON_EDIT') %>
<% end %>
<%= link_to trn_geth('BUTTON_BACK_TO_LIST'), door_glass_families_path %> |
<%= link_to trn_geth('BUTTON_DELETE'), door_glass_family_path(@door_glass_family), :confirm => trn_geth('LABEL_DELETE_QUESTION'), :method => :delete %>

app/views/door_glass_families/index.html.erb
<h2><%= trn_geth('TITLE_DOOR_GLASS_FAMILY_LIST') %></h2>

<%= link_to trn_geth('BUTTON_ADD'), new_door_glass_family_path %>
<table cellspacing="0">
  <tr class="header">
    <th><%= trn_geth('HEADER_NAME') %></th>
    <th></th>
  </tr>
<% for door_glass_family in @door_glass_families %>
  <tr class="<%= cycle('odd', 'even') %>">
    <td><%= door_glass_family.tr_name %></td>
    <td>
      <%= link_to trn_geth('BUTTON_GLASSES'), door_glass_family_door_glasses_path(door_glass_family) %> |
      <%= link_to trn_geth('BUTTON_EDIT'), edit_door_glass_family_path(door_glass_family) %> |
      <%= link_to trn_geth('BUTTON_DELETE'), door_glass_family_path(door_glass_family), :confirm => trn_geth('LABEL_DELETE_QUESTION'), :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

app/views/door_glass_families/new.html.erb
<h2><%= trn_get('TITLE_DOOR_GLASS_FAMILY_ADD') %></h2>

<%= form_for @door_glass_family do |f| %>
  <%= render :partial => 'form' %>
  <%= submit_tag trn_geth('BUTTON_ADD') %>
<% end %>
<%= link_to trn_geth('BUTTON_BACK_TO_LIST'), door_glass_families_path %>