config/routes.rb
GlassVision::Application.routes.draw do

  resources :emails
  match '/signup', :to => 'users#new', :as => :signup
  match '/login', :to => 'session#new', :as => :login
  match '/logout', :to => 'session#destroy', :as => :logout
  match '/activate/:id', :to => 'accounts#show', :as => :activate
  match '/forgot_password', :to => 'passwords#new', :as => :forgot_password
  match '/reset_password/:id', :to => 'passwords#edit', :as => :reset_password
  match '/change_password', :to => 'accounts#edit', :as => :change_password

  resources :users do
    post :enable
    post :disable
    resource :account
    resources :roles
  end

  resources :product_colors
  resources :shapes

  resources :doors do
    collection do
      get 'configure_panels'
      get 'configure_panel_dimensions'
      get 'configure_glass_families'
      get 'configure_glasses'
      get 'configure_openings'
    end
  end
  resources :door_frames
  resources :door_combinations
  resources :frame_profiles
  resources :slab_materials
  resources :door_openings
  resources :door_glass_families do
    resources :door_glasses
  end
  resources :door_panel_families do
    resources :door_panels do
      resources :door_panel_dimensions
    end
  end
  resources :door_borings
  resources :door_sections
  resources :manual_lines

  resource :session, :controller => :session
  resource :passwords
  resources :quotations, :controller => :quotation do
    collection do
        post :search
    end
    post :copy
    get :print
    get :print_invoice
    get :print_calculations
    get :print_manifest
  end
  root :to => 'home#index'

  match '/:controller(/:action(/:id))'
end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
  has_many :quotation_lines, :dependent => :destroy
  has_many :door_lines, :dependent => :destroy
  has_many :options_quotations, :dependent => :destroy
  has_many :manual_lines, :dependent => :destroy
  belongs_to :user
  belongs_to :company

  validates_presence_of :project_name
  validates_numericality_of :markup, :allow_nil => true, :greater_than_or_equal_to => 0, :less_than_or_equal_to => 30
  validates_numericality_of :deposit, :allow_nil => true, :greater_than_or_equal_to => 0

  after_initialize :set_tax_rates

  def set_tax_rates
    if new_record? && !changed?
      self.taxes ||= 5.0
      self.taxes_pst ||= 9.5
    end
  end

  def use_billing_address?
    if (customer_address.nil? || delivery_address.nil?)
     return false
    end

   return customer_address == delivery_address
  end

  def calculate_taxes(total)
   total * self.taxes / 100.0
  end

  def calculate_pst(total)
    if !self.taxes_pst.blank?
      total * self.taxes_pst / 100.0
    else
     0.0
    end
  end

  # given a source quotation, copy to new with derivative slug
  def self.copy(orig_quotation)
    quotation = orig_quotation.clone(:include => [:options_quotations, {:quotation_lines => [:quotation_lines_openings, :options_quotation_lines, :section_heights, :section_widths] }, {:door_lines => [:door_line_sections, :door_line_options]}])
    quotation.slug = quotation.generate_new_slug(orig_quotation.slug)
    quotation
  end

  def regenerate_previews
    quotation_lines.each do |line|
      line.create_image
    end
    door_lines.each do |line|
      line.create_image
    end
  end

  def generate_new_slug(slug)
    last = 1
    base_slug = slug.slice(/.*-/) || slug + "-"
    existing_slugs = Quotation.connection.select_all("select slug from quotations where slug like '#{base_slug}%'")
    existing_slugs = existing_slugs.collect {|s| s["slug"]}
    last = existing_slugs.collect{|s| s[((s.rindex('-')||-1)+1)..-1].to_i}.max() + 1  unless existing_slugs.empty?

    return base_slug + last.to_s
  end
end

app/controllers/quotation_controller.rb
class QuotationController < ApplicationController

  before_filter :find_quotation, :only => [:show, :print, :print_invoice, :print_manifest, :print_calculations]
  sortable_attributes  :updated_at, :slug, :description, :created_by, :consultant

  SEARCH_FIELDS = %w(search_description search_slug)
  def index
    search_params_from_session
    conditions = {:user_id => @current_user.id} unless @current_user.has_role?('administrator')
    @quotations = Quotation.includes(:user).where(conditions).where(search_conditions).paginate(:page => params[:page], :per_page => 25).order(sort_order || "updated_at DESC")
  end

  def show
    if @quotation.user_id != @current_user.id && !@current_user.has_role?('administrator')
      flash[:notice] = trn_geth("PERMISSION_DENIED")
      redirect_to :action => 'index'
    end
  end

  def new
    @quotation = Quotation.new
    @quotation.discount = @current_user.discount
    @users = User.find_all_by_enabled(true)
  end

  def create
    set_taxes_if_not_present()

    @quotation = Quotation.new(params[:quotation])
    @quotation.user_id = @current_user.id
    customer_msg = ""
    if Customer.create_from_quotation_if_new(@quotation)
      customer_msg = trn_geth('LABEL_CUSTOMER') + " " + trn_get('MSG_SUCCESSFULLY_CREATED_F')
    end
    if @quotation.save
    	if @quotation.slug.blank?
    	  @quotation.slug = @quotation.id.to_s
    	  @quotation.save
    	end
      customer_msg += "<br />" unless customer_msg.blank?
      customer_msg +=  trn_geth('LABEL_QUOTATION') + " " + trn_get('MSG_SUCCESSFULLY_CREATED_F')
      flash[notice] = customer_msg.html_safe
      redirect_to :action => 'show', :id => @quotation.slug
    else
      render :action => 'new'
    end
  end

  def edit
    @quotation = Quotation.find_by_slug(params[:id])
    @users = User.find_all_by_enabled(true)
  end

  def update
    set_taxes_if_not_present()

    @quotation = Quotation.find(params[:id])

    if @quotation.update_attributes(params[:quotation])
      flash[:notice] = trn_geth('LABEL_QUOTATION') + " " + trn_get('MSG_SUCCESSFULLY_MODIFIED_F')
      redirect_to :action => 'show', :id => @quotation.slug
    else
      render :action => 'edit'
    end
  end

  def destroy
    Quotation.find_by_slug(params[:id]).destroy
    flash[:notice] = trn_geth('LABEL_QUOTATION') + " " + trn_get('MSG_SUCCESSFULLY_DELETED_F')
    redirect_to :action => 'index'
  end

  def print
    render :layout => 'printer'
  end

  def print_invoice
    render :layout => 'printer'
  end

  def print_manifest
    render :layout => 'printer'
  end

  def print_calculations
    if current_user.has_role?('administrator')
      render :layout => 'printer'
    else
      redirect_to :action => 'index'
    end
  end

  def copy
#    return unless request.xhr?
    @orig_quotation = Quotation.includes(:quotation_lines => [:serie, :shape, {:quotation_lines_openings => :opening}, {:options_quotation_lines=> :option}]).find_by_slug(params[:quotation_id])
    if @orig_quotation.user_id != @current_user.id && !@current_user.has_role?('administrator')
      flash[notice] = trn_get("PERMISSION_DENIED")
      redirect_to :action => 'index'
    end
    @quotation = Quotation.copy(@orig_quotation)
    @quotation.save!
    @quotation.regenerate_previews
    flash[:notice] = trn_geth('LABEL_QUOTATION') + " " + trn_get('MSG_SUCCESSFULLY_CREATED_F')
    redirect_to edit_quotation_path(@quotation.slug)
  end
  def search
    save_search_params_to_session
    params[:action] = "index"

    if @current_user.has_role?('administrator')
      @quotations = Quotation.includes(:user).paginate(:page => params[:page], :order => sort_order, :conditions => search_conditions, :per_page => 25)
    else
      @quotations = Quotation.includes(:user).where("user_id = ?", @current_user.id).paginate(:page => params[:page], :order => sort_order, :conditions => search_conditions, :per_page => 25)
    end

    render :partial => 'quotation_list'
  end

protected
  def search_params_from_session
    SEARCH_FIELDS.each { |x| params[x.to_sym] = session[x.to_sym]}
  end

  def save_search_params_to_session
    SEARCH_FIELDS.each { |x| session[x.to_sym] = params[x.to_sym]}
  end

  def match_beginning(value)
    " like \'#{value}%\'"
  end

  def match_ending(value)
    " like \'%#{value}\'"
  end

  def match_anywhere(value)
    " like \'%#{value}%\'"
  end

  def match_exact(value)
    new_value = value.gsub /\*/, '%'
    " like '#{new_value}'"
  end

  def search_condition_for(field, value)
    return nil if value.blank?
    case field.gsub(/search_/, "")
      when "slug"
        "slug "+ match_anywhere(value)
      when "description"
        "customer_name" + match_anywhere(value)
    end
  end

  def search_conditions
    conditions = SEARCH_FIELDS.collect{|x| search_condition_for(x, params[x.to_sym])}
    conditions = conditions.delete_if{|x| x.nil?}
    conditions.join(" and ")
  end
  def find_quotation
    @quotation = Quotation.includes(:quotation_lines => [:serie, :shape, {:quotation_lines_openings => :opening}, {:options_quotation_lines=> :option}]).find_by_slug(params[:id])
  end

  def set_taxes_if_not_present
    params[:quotation]['taxes']     = 0.0 if params[:quotation]['taxes'].blank?
    params[:quotation]['taxes_pst'] = 0.0 if params[:quotation]['taxes_pst'].blank?
  end

end

app/helpers/quotation_helper.rb
module QuotationHelper
end

app/views/quotation/_door_line.html.erb
  <tr valign="top" class="quotation-line">
    <td width="1%" style="border-bottom: 2px dotted #808080;"><%= image_tag "/system/images/doors/preview_#{door.id}.png" %></td>
    <td style="border-bottom: 2px dotted #808080;">

      <table>
        <tr>
          <td><%= trn_geth('HEADER_DOOR_COMBINATION') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= door.door_combination.tr_name %></td>
        </tr>
        <tr>
          <td><%= trn_geth('HEADER_FRAME_PROFILE') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= door.frame_profile.tr_name %></td>
        </tr>
        <tr>
          <td><%= trn_geth('HEADER_SLAB_MATERIAL') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= door.slab_material.tr_name %></td>
        </tr>
        <% if !door.interior_color.blank? || !door.standard_interior_color.blank? %>
          <tr>
            <td><%= trn_get('LABEL_INTERIOR_COLOR')%></td>
            <td><%= h door.interior_color.blank? ? door.standard_interior_color.tr_name : door.tr_interior_color + trn_get("LABEL_CUSTOM") %></td>
          </tr>
        <% end %>
        <% if !door.exterior_color.blank?  || !door.standard_exterior_color.blank?%>
          <tr>
            <td><%= trn_get('LABEL_EXTERIOR_COLOR')%></td>
            <td><%= h door.exterior_color.blank? ? door.standard_exterior_color.tr_name : door.tr_exterior_color + trn_get("LABEL_CUSTOM") %> </td>
          </tr>
        <% end %>
        <tr>
          <td><%= trn_geth('HEADER_DOOR_OPENING') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= door.door_opening.tr_name %></td>
        </tr>
        <tr>
          <td><%= trn_geth('HEADER_DOOR_BORING') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= door.door_boring.tr_name %></td>
        </tr>
        <% door.door_line_sections.each_with_index do |section, index| %>
        <tr>
          <td valign="top"><%= trn_geth('HEADER_DOOR_SECTION') %> <%= index + 1 %><%= trn_geth('LABEL_SEMICOLON') %></td>
          <td>
            <%= trn_geth('HEADER_DOOR_SECTION') %> <%= trn_geth('LABEL_SEMICOLON') %> <%= section.door_section.tr_name %><br/>
            <% if section.door_panel %>
              <%= trn_geth('HEADER_DOOR_PANEL') %> <%= trn_geth('LABEL_SEMICOLON') %> <%= section.door_panel.tr_name %><br/>
            <% end %>
            <% if section.door_glass %>
              <%= trn_geth('HEADER_DOOR_GLASS') %> <%= trn_geth('LABEL_SEMICOLON') %> <%= section.door_glass.door_glass_family.tr_name %> / <%= section.door_glass.tr_name %><br/>
            <% end %>
            <%= trn_geth('HEADER_DOOR_PANEL_HEIGHT') %> <%= trn_geth('LABEL_SEMICOLON') %> <%= section.door_panel_dimension.try(:height) %>" x
            <%= trn_geth('HEADER_DOOR_PANEL_WIDTH') %> <%= trn_geth('LABEL_SEMICOLON') %> <%= section.door_panel_dimension.try(:width) %>"<br/>
          </td>
        </tr>
        <% end %>
        <% if door.door_line_options.length > 0 %>
        <tr>
          <td valign="top"><%= trn_geth('HEADER_OPTIONS') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td>
            <% for option in door.door_line_options %>
              <%= option.option.tr_description %>
              <% if option.quantity != 1 %>
                x <%= option.quantity %>
              <% end %>
              <br/>
            <% end %>
          </td>
        </tr>
        <% end %>
        <tr>
          <td><%= trn_geth('HEADER_UNIT_PRICE') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= format('%.2f', door_price) %>$</td>
        </tr>
        <tr>
          <td><%= trn_geth('HEADER_QUANTITY') %> <%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= door.quantity %></td>
        </tr>
      </table>

    </td>
    <td align="right" style="border-bottom: 2px dotted #808080;"><%= format('%.2f', door.quantity * door.price) %>$</td>
    <td nowrap="nowrap" style="border-bottom: 2px dotted #808080;">
      <%= link_to trn_geth('BUTTON_EDIT'), edit_door_path(door) %> |
      <%= link_to trn_geth('BUTTON_DELETE'), door_path(door), :confirm => trn_geth('LABEL_DELETE_QUESTION'), :method => :delete %>
    </td>
  </tr>

app/views/quotation/_form.html.erb
<%= error_messages_for "quotation" %>

<table>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_DESCRIPTION') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field "quotation", "description", :size => 50%></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_COMMENTS') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_area "quotation", "comments", :cols => "39", :rows => "7" %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_PROJECT_NAME') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field "quotation", "project_name", :size => 50 %><strong> *</strong></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_CUSTOMER_NAME') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field :quotation, :customer_name, :size => 50  %>
      <%= ajax_spinner_for('quotation_customer_name').html_safe %>
    </td>
    <div class="auto_complete" id="quotation_customer_name_auto_complete"></div>
    <%= auto_complete_field :quotation_customer_name,
                            :url => { :controller => 'customer', :action => 'autocomplete_for_name'},
                            :indicator => 'quotation_customer_name_spinner',
                            :after_update_element => "function(element,value){" + remote_function(:url => {
                                    :controller => :customer, :action => :show_by_name },
                                    :with =>"'customer_name='+element.value") + "}"
    %>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_CUSTOMER_NAME_PICK') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= select("customer", "name", Customer.all().collect(&:name)) %>
    </td>
    <%= observe_field :customer_name,
        :on => 'onchanged',
        :url => { :controller => 'customer', :action => 'show_by_name'},
        :with =>"'customer_name='+element.value"
    %>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_CUSTOMER_ADDRESS') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_area "quotation", "customer_address", :cols => "39", :rows => "5", :id => 'customer_address'  %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_DELIVERY_ADDRESS') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_area "quotation", "delivery_address", :cols => "39", :rows => "5", :id => 'delivery_address'  %>
      <br />
      <%= check_box_tag 'use_billing_address', @quotation.use_billing_address?-%><%= trn_get('LABEL_SAME_DELIVERY_ADDRESS') -%>

      <%= observe_field 'use_billing_address',
         {
         :function => 'updateShippingAddress(this.checked)',
         :frequency => 0.3,
         :on => 'onclicked'
         }
      %>
    </td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_CUSTOMER_PHONE') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field "quotation", "customer_phone", :size => 50, :id => 'customer_phone'  %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_CUSTOMER_FAX') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field "quotation", "customer_fax", :size => 50, :id => 'customer_fax'  %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_CUSTOMER_EMAIL') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field "quotation", "customer_email", :size => 50, :id => 'customer_email'  %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_NOTES') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_area "quotation", "notes", :cols => "39", :rows => "5"  %></td>
  </tr>
</table>
<hr/>
<table>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_TRANSPORT') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field "quotation", "transport", :size => 10, :style => "text-align: right;" %>$</td>
  </tr>
  <% if current_user.has_role?('administrator')%>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_DISCOUNT') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field "quotation", "discount", :size => 10, :style => "text-align: right;" %>%</td>
  </tr>
  <% else %>
    <%= hidden_field "quotation", "discount" %>
  <% end %>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_MARKUP') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field "quotation", "markup", :size => 10, :style => "text-align: right;" %>%</td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_get('LABEL_TAXES') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field "quotation", "taxes", :size => 10, :style => "text-align: right;" %>%</td>
  </tr>  
  <tr valign="top">
    <td align="right"><%= trn_get('LABEL_PST_RATE') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field "quotation", "taxes_pst", :size => 10, :style => "text-align: right;" %>%</td>
  </tr>  
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_DEPOSIT') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field "quotation", "deposit", :size => 10, :style => "text-align: right;" %>$</td>
  </tr>  
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_QUOTE_READY_TO_SIGN') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= check_box "quotation", "ready_to_sign" %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_COMPANY') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= select 'quotation', 'company_id', @current_user.active_companies.map { |c| [c.name, c.id] } %></td>
  </tr>
  <tr valign="top">
    <td align="right"><%= trn_geth('LABEL_CONSULTANT') %><%= trn_geth('LABEL_SEMICOLON') %></td>
    <td><%= text_field 'quotation', 'consultant',  :size => 50  %></td>
  </tr>
</table>

app/views/quotation/_manual_line.html.erb
  <tr valign="top" class="quotation-line">
    <td colspan="1" style="border-bottom: 2px dotted #808080;">
    </td>
    <td colspan="1" style="border-bottom: 2px dotted #808080;">
      <table>
        <tr>
          <td><%= trn_geth('HEADER_DESCRIPTION') %><%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= option.description %> </td>
        </tr>
        <tr>
          <td><%= trn_geth('HEADER_UNIT_PRICE') %><%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= format('%.2f',  option_price) %>$</td>
        </tr>
        <tr>
          <td><%= trn_geth('HEADER_QUANTITY') %><%= trn_geth('LABEL_SEMICOLON') %></td>
          <td><%= option.quantity %></td>
        </tr>
      </table>
    </td>
    <td align="right" style="border-bottom: 2px dotted #808080;"><%= format('%.2f', option.quantity * option_price) %>$</td>
    <td nowrap="nowrap" style="border-bottom: 2px dotted #808080;">
      <%= link_to trn_geth('BUTTON_EDIT'), :controller => 'manual_lines', :action => 'edit', :id => option.id %> |
      <%= link_to trn_geth('BUTTON_DELETE'), {:controller => 'manual_lines', :action => 'delete', :id => option.id}, :confirm => trn_geth('LABEL_DELETE_QUESTION') %>
    </td>
  </tr>

app/views/quotation/_quotation_list.html.erb
<%= will_paginate @quotations, :class => "apple_pagination", :next_label => trn_get('NEXT_PAGE'), :previous_label => trn_get('PREVIOUS_PAGE') %>

<table cellspacing="0" style="width:100%;">
  <thead class="header">
  <%= sortable_table_header :name => trn_geth('HEADER_NUMBER'),  :sort => "slug", :page => params[:page] %>
  <%= sortable_table_header :name => trn_geth('HEADER_DATE_MODIFIED'),  :sort => "updated_at", :page => params[:page] %>
  <%= sortable_table_header :name => trn_geth('HEADER_DESCRIPTION'),  :sort => "description", :page => params[:page] %>
  <%= sortable_table_header :name => trn_geth('HEADER_CREATED_BY'),  :sort => "created_by", :page => params[:page] if @current_user.has_role?('administrator') %>
  <%= sortable_table_header :name => trn_geth('LABEL_CONSULTANT') ,  :sort => "consultant", :page => params[:page] if @current_user.has_role?('administrator')%>
  <th></th>
  </thead>
  <tbody>
  <tr>
    <td><%= text_field_tag :search_slug, params[:search_slug], :style=>"width:100%" %></td>
    <td></td>
    <td><%= text_field_tag :search_description, params[:search_description], :style=>"width:100%" %></td>
    <td></td>
    <td></td>
    <td><%= image_tag("spinner.gif", :align => "absmiddle", :border => 0, :id => "loading", :style =>"display: none;" ) %>
    </td>
  </tr>
  <% @quotations.each do |quotation| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= quotation.slug %></td>
        <td><%= gv_humanize_time quotation.updated_at %></td>
        <td><%= link_to quotation.project_name, quotation_path(quotation.slug) %><%= ' (' + quotation.description + ')' unless quotation.description.blank? %><br/>
            <%= quotation.customer_name %>
        </td>
        <td><%= quotation.user.login  if @current_user.has_role?('administrator') and !quotation.user.nil? %> </td>
        <td><%= quotation.consultant  if @current_user.has_role?('administrator') and !quotation.consultant.nil? %> </td>
        <td style="width: 115px;">
          <%= link_to image_tag('copy.png', :title => trn_geth('BUTTON_COPY')), quotation_copy_path(quotation.slug), :method => :post %>
          <%= link_to image_tag('page_white_edit.png', :title => trn_geth('BUTTON_EDIT')), edit_quotation_path(quotation.slug) %>
          <%= link_to image_tag('delete.png', :title => trn_geth('BUTTON_DELETE')), {:action => 'destroy', :id => quotation.slug}, :method => :delete, :confirm => trn_geth('LABEL_DELETE_QUESTION') %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @quotations, :class => "apple_pagination", :next_label => trn_get('NEXT_PAGE'), :previous_label => trn_get('PREVIOUS_PAGE') %>

<%= page_entries_info @quotations %>

app/views/quotation/edit.html.erb
<h2><%= trn_get('TITLE_QUOTATION_EDIT') %></h2>

<%= form_for  @quotation do %>
  <%= render :partial => 'form' %>
  <br />
  <div class="form_button_bar submit" >
    <%= css_button_to trn_geth('BUTTON_BACK_TO_LIST'), :action => 'index' %> 
    <%= css_button_to trn_geth('BUTTON_DELETE'), {:action => 'destroy', :id => @quotation.slug}, :confirm => trn_geth('LABEL_DELETE_QUESTION') %>
    <%= css_button_to trn_geth('BUTTON_SHOW'), :action => 'show', :id => @quotation.slug %>
    <%= submit_tag trn_geth('BUTTON_EDIT') %>
  </div>
  <% end %>

app/views/quotation/index.html.erb
<h2><%= trn_geth('TITLE_QUOTATION_LIST') %></h2>

<%= link_to trn_geth('BUTTON_ADD'), new_quotation_path %>

<%= form_remote_tag :url => search_quotations_path, :id => 'search-form', :update => "results", :loading => "toggleLoading();" do %>
  <div id="results">
    <%= render :partial => 'quotation_list' %>
  </div>
  <%= submit_tag "Search", :style => "display:none;"%>
<% end %>

<script type="text/javascript">
      // create a convenient toggleLoading function
      var toggleLoading = function() {
          jQuery("#loading").toggle()
      };
</script>

app/views/quotation/new.html.erb
<h2><%= trn_get('TITLE_QUOTATION_ADD') %></h2>

<%= form_tag :action => 'create' do %>
  <%= render :partial => 'form' %>
  <%= submit_tag trn_geth('BUTTON_ADD') %>
<% end %>
<%= link_to trn_geth('BUTTON_BACK_TO_LIST'), quotations_path %>

app/views/quotation/show.html.erb
<h2><%= trn_geth('TITLE_QUOTATION_SHOW') %></h2>

<%= render :partial => 'show' %>